"""Canonical conformance result taxonomy."""

PASS = "PASS"
DRIFT = "DRIFT"
FAIL = "FAIL"
BLOCKED = "BLOCKED"
NOT_APPLICABLE = "NOT_APPLICABLE"
UNOBSERVED = "UNOBSERVED"

TERMINAL_STATUSES = (PASS, DRIFT, FAIL, BLOCKED, NOT_APPLICABLE, UNOBSERVED)
NON_PASSING_STATUSES = (DRIFT, FAIL, BLOCKED, NOT_APPLICABLE, UNOBSERVED)
